### ISSUE TITLE
not completed task

### ISSUE THREAD

**Issue by dzhivushko** [panasik/home_work#4]
https://github.com/panasik/home_work/blob/b66935eb8db303ff0f5862bf4881cab32698fe6b/src/by/itacademy/wp/task6/DatePlus.java#L3-L15

I assume the goal of this task was to create the complex algorithm which can handle date overload. for example if you enter December, 31, then it should show January,1. In your code it will show December 32.

**Comment by panasik** [comment]
Неправильно понял задание
