### ISSUE TITLE
not optimal solution

### ISSUE THREAD

**Issue by dzhivushko** [panasik/home_work#5]
https://github.com/panasik/home_work/blob/b66935eb8db303ff0f5862bf4881cab32698fe6b/src/by/itacademy/wp/task7/HomeAndArea.java#L1-L28

your code checks only 1 variant of building location inside area.  but idea is to calculate different variants of buildings location. It means that shorter area can also be valid for described case. But your solution will require much more square always.

**Comment by panasik** [comment]
Неправильно понял задания. Исходил из того, что неизвестно как расположены здания, и при любом раскладе они должны помещаться.
