### ISSUE TITLE
is a valid solution?

### ISSUE THREAD

**Issue by dzhivushko** [panasik/home_work#6]
https://github.com/panasik/home_work/blob/b66935eb8db303ff0f5862bf4881cab32698fe6b/src/by/itacademy/wp/task8/Faktorial.java#L13
may be I didn't understand some details. but I assume it should be simply x++ for 'factorial'. do not understand why it uses Random inside 'while'

**Comment by panasik** [comment]
Необходимо изменить пример, который отражен на странице 25.  Вместо средней арифметической найти факториал, в котором указано, что ввод чисел прекращается если следующее случайное число равно 0.
